### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by unegare** [docker-library/mongo#432]
docker-compose.yaml
```
version: "3.1"
services:
  mongo:
    image: "mongo"
    restart: "always"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_DATABASE: "test"
  node:
    build: .
    environment:
      MONGO_USER: "root"
      MONGO_PASS: "example"
    depends_on:
      - "mongo"
```

Dockerfile
```
FROM node:latest

WORKDIR /app

COPY . .

ENTRYPOINT ["npm", "run", "start"]
```

package.json
```
{
  "name": "ex_001",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./ex_001.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^5.10.13"
  }
}
```

ex_001.js
```
const mongoose = require('mongoose');
const linkUrl = `mongodb://${process.env['MONGO_USER']}:${process.env['MONGO_PASS']}@mongo:27017/test`;
console.log(`linkUrl: ${linkUrl}`);
mongoose.connect(linkUrl, {useNewUrlParser: true, useUnifiedTopology: true});

const Cat = mongoose.model('Cat', {name: String});

const kitty = new Cat({name: 'Zibl'});
kitty.save().then(() => {console.log('meow')});
```

Logs:
```node_1   | 
node_1   | > ex_001@1.0.0 start
node_1   | > node ./ex_001.js
node_1   | 
node_1   | linkUrl: mongodb://root:example@mongo:27017/test
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.977+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:37806","connectionId":1,"connectionCount":1}}
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.982+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"172.18.0.3:37806","client":"conn1","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.6.3"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.4.0-52-generic"},"platform":"'Node.js v15.1.0, LE (unified)","version":"3.6.3|5.10.13"}}}
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.987+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:37808","connectionId":2,"connectionCount":2}}
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.989+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"172.18.0.3:37808","client":"conn2","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.6.3"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.4.0-52-generic"},"platform":"'Node.js v15.1.0, LE (unified)","version":"3.6.3|5.10.13"}}}
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.991+00:00"},"s":"I",  "c":"ACCESS",   "id":20251,   "ctx":"conn2","msg":"Supported SASL mechanisms requested for unknown user","attr":{"user":"root@test"}}
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.991+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn2","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","principalName":"root","authenticationDatabase":"test","client":"172.18.0.3:37808","result":"UserNotFound: Could not find user \"root\" for db \"test\""}}
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.992+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn2","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-1","principalName":"root","authenticationDatabase":"test","client":"172.18.0.3:37808","result":"UserNotFound: Could not find user \"root\" for db \"test\""}}
mongo_1  | {"t":{"$date":"2020-11-07T07:00:57.995+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"172.18.0.3:37806","connectionId":1,"connectionCount":1}}
node_1   | /app/node_modules/mongodb/lib/cmap/connection.js:268
node_1   |           callback(new MongoError(document));
node_1   |                    ^
node_1   | 
node_1   | MongoError: Authentication failed.
node_1   |     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:268:20)
node_1   |     at MessageStream.emit (node:events:327:20)
node_1   |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
node_1   |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
node_1   |     at writeOrBuffer (node:internal/streams/writable:388:12)
node_1   |     at MessageStream.Writable.write (node:internal/streams/writable:333:10)
node_1   |     at Socket.ondata (node:internal/streams/readable:715:22)
node_1   |     at Socket.emit (node:events:327:20)
node_1   |     at addChunk (node:internal/streams/readable:304:12)
node_1   |     at readableAddChunk (node:internal/streams/readable:279:9)
node_1   |     at Socket.Readable.push (node:internal/streams/readable:218:10)
node_1   |     at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
node_1   |   ok: 0,
node_1   |   code: 18,
node_1   |   codeName: 'AuthenticationFailed'
node_1   | }
```

inside the container:
```
$ docker exec -it 67e0e79c755e bash
root@67e0e79c755e:/# mongo
MongoDB shell version v4.4.1
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("d73a3b11-b644-41f0-9e6b-f6899512dcd6") }
MongoDB server version: 4.4.1
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	https://docs.mongodb.com/
Questions? Try the MongoDB Developer Community Forums
	https://community.mongodb.com
> db.auth('root', 'example')
Error: Authentication failed.
0
> 
```

**Comment by wglambert** [comment]
>"UserNotFound: Could not find user \"root\" for db \"test\""

You should include `--authenticationDatabase admin`

The `MONGO_INITDB_DATABASE: "test"` is just for `*.js` scripts in `/docker-entrypoint-initdb.d/` when initializing a new instance
https://github.com/docker-library/docs/tree/master/mongo#mongo_initdb_database

**Comment by unegare** [comment]
> > "UserNotFound: Could not find user "root" for db "test""
> 
> You should include `--authenticationDatabase admin`
> 
> The `MONGO_INITDB_DATABASE: "test"` is just for `*.js` scripts in `/docker-entrypoint-initdb.d/` when initializing a new instance
> https://github.com/docker-library/docs/tree/master/mongo#mongo_initdb_database

Could you make it clear where and how in `docker-compose.yaml` I should specify this?

**Comment by wglambert** [comment]
That's part of the argument for connecting to mongo
https://stackoverflow.com/a/29801077

**Comment by yosifkit** [comment]
For the `mongo` shell, you should probably pass it beforehand as @wglambert has shown (`mongo --username "root" --password "example" --authenticationDatabase admin`), or you'll probably have to do a `use admin` before the `db.autth`.

For your js using `mongoose`, the equivalent setting would be `authSource`:

> authSource - The database to use when authenticating with user and pass. In MongoDB, users are scoped to a database. If you are getting an unexpected login failure, you may need to set this option.
>
> https://mongoosejs.com/docs/connections.html

**Comment by unegare** [comment]
Solved. Thank you!
