### ISSUE TITLE
Cannot run mongodb/mongodb-community-server:latest on Mac M2

### ISSUE THREAD

**Issue by spitfiredd** [docker-library/mongo#652]
I am trying to run a mongodb container with `--platform linux/amd` on a Mac M2;

Command:
```
docker run --name mongodb -d -p 27017:27017 mongodb/mongodb-community-server:latest
```

I get the following error:

```
2023-12-07 08:57:50 Traceback (most recent call last):
2023-12-07 08:57:50   File "/usr/local/bin/docker-entrypoint.py", line 637, in <module>
2023-12-07 08:57:50     subprocess.run(get_final_command_line_args(), check=True)
2023-12-07 08:57:50   File "/usr/lib/python3.10/subprocess.py", line 526, in run
2023-12-07 08:57:50     raise CalledProcessError(retcode, process.args,
2023-12-07 08:57:50 subprocess.CalledProcessError: Command '['mongod', '--bind_ip_all']' died with <Signals.SIGILL: 4>.
```

I have no problem running other `linux/amd` docker container sand the `arm` version of this docker image works fine.

**Comment by tianon** [comment]
Unfortunately, that image isn't actually maintained in this repository :sweat_smile:

Looking at https://hub.docker.com/r/mongodb/mongodb-community-server, it looks like they suggest one of these:

> Where to get help: [MongoDB Documentation](https://www.mongodb.com/docs/), [MongoDB Community](https://www.mongodb.com/community/forums/), [Technical Support](https://support.mongodb.com/?_ga=2.160125560.455708262.1673982856-741025604.1637357550)
